package(default_visibility = ["//visibility:public"])

cc_library(
  name = "aby3_test_lib",
  hdrs = glob(["*.h"]),
  srcs = glob(["*.cpp"]),
  deps = [
    "//aby3:aby3_lib",
    "@ladnir_cryptoTools//:tests_cryptoTools",
  ],
)